### ISSUE TITLE
can't scrape games because of URL Updater

### ISSUE THREAD

**Issue by arridian8** [Rocky5/XBMC-Emustation#83]
Hi everyone, 
I scanned my OG Xbox with Emustation to discover the Sega CD games I put on it. That went fine. But when I tried to scrape Sega CD for cover art, it said I needed to update URL Downloader. I did, but now it constantly asks for the URL Downloader to be updated. Also, my  Sega CD games don't work. I get a black screen and it goes back to the Unleash X screen.  I am using the latest version of Emustation. Can someone help me?

**Comment by Rocky5** [comment]
Head to file manager > Q > emustation > scripts > urldownloader > and select force update.py

it will download the urldownloader. You will be asked again to update, this is normal now as it’s loading the links to the new download location. 

When done, install the correct SegaCD emulators, if you’re using ISO/MP3 you need the one of the downloader.

**Comment by arridian8** [comment]
Thanks so much for responding. I found the force update.py, but when I select it with the A button, it doesn't do anything. Also, my SegaCD files are in the bin/cue format. Is that normal? Sorry, I only have a moderate knowledge of Xbox and Emustation.

**Comment by Rocky5** [comment]
> Thanks so much for responding. I found the force update.py, but when I select it with the A button, it doesn't do anything. Also, my SegaCD files are in the bin/cue format. Is that normal? Sorry, I only have a moderate knowledge of Xbox and Emustation.

By default bin/cue is set. You need to toggle the scanner option for IOS/MP3 and download an emulator. So if you haven’t done either then it’s setup correctly. 

Retry the downloader, i fixed the force update script and also updated the old downloader locations files. (You download this one and it will always update from the new location)

**Comment by arridian8** [comment]
URL Downloader has updated and is working fine. Thanks so much. Still having problems with SegaCD. Downloaded one emulator from the downloads section of Emustation. Upon executing a game, it went back to X Unleashed. Downloaded the 2nd one and it just gives me a black screen. I checked and all the games are in their own folders in the rom/segacd folder.

**Comment by Rocky5** [comment]
> URL Downloader has updated and is working fine. Thanks so much. Still having problems with SegaCD. Downloaded one emulator from the downloads section of Emustation. Upon executing a game, it went back to X Unleashed. Downloaded the 2nd one and it just gives me a black screen. I checked and all the games are in their own folders in the rom/segacd folder.

bin/cue dont go in folders, they all go in the root of the segacd folder.

If you had the scanner option enabled for segaCD then it will have folderized them. But again, bin/cue dont go in folders.

**Comment by arridian8** [comment]
Hi, I hate to bother you again, but today I'm having the same problems as I had last night. URL Downloader keeps asking to be updated when I try to download the SegaCD games artwork. I re-FTP'd the SegaCD files into the SegaCD folder as is without each game being foldered, and upon execution of a game, takes me back to the Unleash X screen.

**Comment by Rocky5** [comment]
> Hi, I hate to bother you again, but today I'm having the same problems as I had last night. URL Downloader keeps asking to be updated when I try to download the SegaCD games artwork. I re-FTP'd the SegaCD files into the SegaCD folder as is without each game being foldered, and upon execution of a game, takes me back to the Unleash X screen.

Manually update, via the update tab. It’s fixed now, but your script is looking at the old address.

**Comment by arridian8** [comment]
Could you tell me how I can get to find the update tab? I'm sorry, I don't know much about Emustation.

**Comment by Rocky5** [comment]
> Could you tell me how I can get to find the update tab? I'm sorry, I don't know much about Emustation.

When in the downloader, the bottom tab.

**Comment by arridian8** [comment]
Okay the URL Updater is working now. I tried downloading a SegaCD emulator (I picked the 2nd one because it apparently works with bin/cue files) and those games still won't load. Thanks so much for your patience. It's very much appreciated.

**Comment by Rocky5** [comment]
> Okay the URL Updater is working now. I tried downloading a SegaCD emulator (I picked the 2nd one because it apparently works with bin/cue files) and those games still won't load. Thanks so much for your patience. It's very much appreciated.

Make sure your bin cue files aren’t in folders and are just plonked in the segacd folder under roms. 

Also make sure your cue file points to the bin file/s open it with a text editor and look at the first line. 

If that still doesn’t work, get new files 😂 or just the iso/mp3 as they are under half the size and work the same. 

Oh also make sure you rescan segacd after changing stuff to do with the roms folder.

**Comment by arridian8** [comment]
Great news. I downloaded the iso/mp3 versions of the SegaCD games and it is working much better. Thank you for all you do with Emustation and your other projects.
